### ISSUE TITLE
Consider supporting listenbrainz

### ISSUE THREAD

**Issue by datn** [willmanduffy/scrobble-blue#2]
https://listenbrainz.org/about/ is an alternative scrobbling target.

https://listenbrainz.readthedocs.io/en/latest/

**Comment by willmanduffy** [comment]
@datn Thanks for the request! I've merged this in. Last.FM and ListenBrainz will work in tandem if anyone ever ends up using both. 

I probably won't get to #1 for a tiny bit. You're welcome to take a crack at that if interested but otherwise I'll loop back to it.
